package searchgem5.gen.llm;

import java.util.Random;

class LLMTokensOptions {
    private static final Random random = new Random();

    public final String[] m_compilerOpt = {
            "Scalar Optimizations", "Dead Code Elimination", "Constant Folding", "Common Subexpression Elimination",
            "Loop Optimizations", "Loop Optimizations", "Loop Fusion", "Loop-Invariant Code Motion",
            "Memory Optimizations", "Memory-to-Register Promotion", "Sparse Conditional Constant Propagation",
            "Inlining", "Function Inlining", "Inliner Heuristics",
            "Target-Specific Optimizations", "Instruction Scheduling", "Register Allocation",
            "Interprocedural Optimizations", "Whole Program Analysis", "Function Specialization",
            "Profile-Guided Optimizations", "Profile-Guided Instrumentation", "Profile-Guided Optimization",
            "Vectorization", "Automatic Vectorization", "Loop Vectorization"
    };
    public final String[] m_compilerParts = {
            "Code Generation", "Handles code generation", "Supports execution of generated code", "Handles machine code generation",
            "Deals with object file manipulation", "Targets specific architectures",
            "Assembly and Bitcode", "Parses assembly files", "Handles LLVM bitcode",
            "Support", "Provides various utility functions",
            "Analysis", "Static analysis in Clang", "General LLVM analysis passes",
            "IR Manipulation", "Core LLVM Intermediate Representation (IR) manipulation", "Reads LLVM IR",
            "Object and Binary Format", "Deals with binary formats",
            "Passes and Transformations", "Collection of optimization passes", "Framework for LLVM transformations",
            "Frontend", "Header files for Clang frontend", "Handles Abstract Syntax Tree (AST)", "Implements Clang frontend",
            "Support Libraries",
            "Backend", "Middle-End", "Frontend", "StaticAnalyzer", "Sema", "Serialization", "Parse", "Lex", "AST"
    };
    public final String[] m_PL = {
            "Integer", "Floating-Point Numbers", "ASCII Value of a Character", "Print", "Compute Quotient and Remainder",
            "int, float, double and char", "sizeof", "Keyword long", "Swap Two Numbers", "Number is Even or Odd",
            "A character is a Vowel or Consonant", "Largest Number Among Three Numbers", "binary operators",
            "short circuiting rule", "short circuit", "Roots of a Quadratic Equation", "logic expression", "expression",
            "expression not zero", "expression positive", "expression negative", "expression negative or positive",
            "Leap Year", "a Number is Positive or Negative", "a Character is an Alphabet or not", "the Sum of Natural Numbers",
            "calculate two numbers result", "Factorial of a Number", "Generate Multiplication Table", "Generate",
            "Fibonacci Sequence", "GCD of two Numbers", "LCM of two Numbers", "Characters from A to Z Using Loop", "Loop", "For loop",
            "Case switch", "Count Number of Digits in an Integer", "Reverse a Number", "Calculate the Power of a Number",
            "a Number is Palindrome or Not", "Number is Prime or Not", "Prime Numbers Between Two Intervals", "Armstrong Number",
            "Armstrong Number Between Two Intervals", "Factors of a Number", "Simple Calculator Using switch...case",
            "Prime Numbers Between Intervals Using Function", "Prime or Armstrong Number Using User-defined Function", "User-defined Function",
            "Macros", "function", "foo function", "Recursion", "logical", "logic", "time in AM-PM format", "Digital Clock with the Current Time",
            "Calendar Year in Different Formats", "Dates", "Time", "Structure in C", "Structures and Sort them by Age or ID",
            "Passing Structure to a Function", "Complex numbers", "N Distances Given in inch-feet System using Structures",
            "Structures and Sort them by Name", "Students Using Structure", "Union", "int32", "Singly Linked List using Recursion",
            "List", "array", "heap", "Array of Strings", "regex", "null", "null pointer check", "check before dividing",
            "Number of Sub-Strings ", "Array Rotation ", "Two Arrays", "merge", "element in array", "min", "max", "const",
            "C Program to Sort an Array using Bubble Sort",
            "C Program to Sort an Array using Merge Sort",
            "C Program to Sort an Array Using Selection Sort",
            "C Program to Sort an Array Using Insertion Sort",
            "C Program For Boolean to String Conversion",
            "C Program For Float to String Conversion",
            "C Program For Double to String Conversion",
            "C Program For String to Long Conversion",
            "C Program For Long to String Conversion",
            "C Program For Int to Char Conversion",
            "C Program For Char to Int Conversion",
            "C Program For Octal to Decimal Conversion",
            "C Program For Decimal to Octal Conversion",
            "C Program For Hexadecimal to Decimal Conversion",
            "C Program For Decimal to Hexadecimal Conversion",
            "C Program For Decimal to Binary Conversion",
            "C Program For Binary to Decimal Conversion",
            "C Program to Print an Integer (Entered by the User)",
            "C Program to Add Two Integers",
            "C Program to Multiply Two Floating-Point Numbers",
            "C Program to Find ASCII Value of a Character",
            "C Program to Compute Quotient and Remainder",
            "C Program to Find the Size of int, float, double and char",
            "C Program to Demonstrate the Working of Keyword long",
            "C Program to Swap Two Numbers",
            "C Program to Check Whether a Number is Even or Odd",
            "C Program to Check Whether a Character is a Vowel or Consonant",
            "C Program to Find the Largest Number Among Three Numbers",
            "C Program to Find the Roots of a Quadratic Equation",
            "C Program to Check Leap Year",
            "C Program to Check Whether a Number is Positive or Negative",
            "C Program to Check Whether a Character is an Alphabet or not",
            "C Program to Calculate the Sum of Natural Numbers",
            "C Program to Find Factorial of a Number",
            "C Program to Generate Multiplication Table",
            "C Program to Display Fibonacci Sequence",
            "C Program to Find GCD of two Numbers",
            "C Program to Find LCM of two Numbers",
            "C Program to Display Characters from A to Z Using Loop",
            "C Program to Count Number of Digits in an Integer",
            "C Program to Reverse a Number",
            "C Program to Calculate the Power of a Number",
            "C Program to Check Whether a Number is Palindrome or Not",
            "C Program to Check Whether a Number is Prime or Not",
            "C Program to Display Prime Numbers Between Two Intervals",
            "C Program to Check Armstrong Number",
            "C Program to Display Armstrong Number Between Two Intervals",
            "C Program to Display Factors of a Number",
            "C Program to Make a Simple Calculator Using switch...case",
            "C Program to Display Prime Numbers Between Intervals Using Function",
            "C Program to Check Prime or Armstrong Number Using User-defined Function",
            "C Program to Check Whether a Number can be Expressed as Sum of Two Prime Numbers",
            "C Program to Find the Sum of Natural Numbers using Recursion",
            "C Program to Find Factorial of a Number Using Recursion",
            "C Program to Find G.C.D Using Recursion",
            "C Program to Convert Binary Number to Decimal and vice-versa",
            "C Program to Convert Octal Number to Decimal and vice-versa",
            "C Program to Convert Binary Number to Octal and vice-versa",
            "C Program to Reverse a Sentence Using Recursion",
            "C program to calculate the power using recursion",
            "C Program to Calculate Average Using Arrays",
            "C Program to Find Largest Element in an Array",
            "C Program to Calculate Standard Deviation",
            "C Program to Add Two Matrices Using Multi-dimensional Arrays",
            "C Program to Multiply Two Matrices Using Multi-dimensional Arrays",
            "C Program to Find Transpose of a Matrix",
            "C Program to Multiply two Matrices by Passing Matrix to a Function",
            "C Program to Access Array Elements Using Pointer",
            "C Program Swap Numbers in Cyclic Order Using Call by Reference",
            "C Program to Find Largest Number Using Dynamic Memory Allocation",
            "C Program to Find the Frequency of Characters in a String",
            "C Program to Count the Number of Vowels, Consonants and so on",
            "C Program to Remove all Characters in a String Except Alphabets",
            "C Program to Find the Length of a String",
            "C Program to Concatenate Two Strings",
            "C Program to Copy String Without Using strcpy()",
            "C Program to Sort Elements in Lexicographical Order (Dictionary Order)",
            "C Program to Store Information of a Student Using Structure",
            "C Program to Add Two Distances (in inch-feet system) using Structures",
            "C Program to Add Two Complex Numbers by Passing Structure to a Function",
            "C Program to Calculate Difference Between Two Time Periods",
            "C Program to Store Information of Students Using Structure",
            "C Program to Store Data in Structures Dynamically",
            "C Program to Write a Sentence to a File",
            "C Program to Read the First Line From a File",
            "C Program to Display its own Source Code as Output",
            "C Program to Print Pyramids and Patterns",
            "Short circuit and operator precedence", "using scalars with short-circuiting or",
            "Order of evaluation between logical and assignment operators", "a function call",
            "input include several arguments", "Checking dictionary key existence and boolean condition",
            "Short Circuit Evaluation", "Something cool!", "Anything popular in C", "recursion",
            "short circuiting operations", "conditions of short circuit", "use a value without computing it twice",
            "Ternary operator", "Ternary operator use with short circuiting operations",
            "Character sets", "Character display semantics", "limits of integers",
            "Types", "while", "For and While loops", "size_t", "Complex numbers", "malloc", "EOF", "STDC",
            "struct, union or enum, tv_sec", "sqrt", "! (exclamation-mark punctuator),",
            "! (logical negation operator)", "!= (inequality operator)", "!= (not-equal punctuator)",
            "# (hash punctuator)", "# preprocessing directive", "# punctuator", "#define preprocessing directive",
            "#elif preprocessing directive", "#else preprocessing directive", "#endif preprocessing directive",
            "#error preprocessing directive", "#if preprocessing directive", "#if preprocessing directive",
            "#ifdef preprocessing directive", "#ifndef preprocessing directive", "#include preprocessing directive",
            "#line preprocessing directive", "#pragma preprocessing directive", "#undef preprocessing directive",
            "& (bitwise AND operator)", "&& (logical AND operator)", "&= (bitwise AND assignment operator)",
            "’ ’ (space character)", "( (opening parenthesis punctuator)", "() (cast operator)",
            "() (function-call operator)", "() (parentheses punctuator)", "(){} (compound-literal operator)",
            ") (closing parenthesis punctuator)", "* (asterisk punctuator)", "* (indirection operator)",
            "* (multiplication operator)", "*= (asterisk-equal punctuator)", "*= (multiplication assignment operator)",
            "+ (addition operator)", "+ (plus punctuator)", "+ (unary plus operator)", "++ (plus-plus punctuator)",
            "++ (postfix increment operator)", "++ (prefix increment operator)", "+= (addition assignment operator)",
            "+= (plus-equal punctuator)", ", (comma operator)", ", (comma punctuator)",
            "- (minus punctuator)", "- (subtraction operator)", "- (unary minus operator)", "- format flag",
            "-- (minus-minus punctuator)", "-- (postfix decrement operator)", "-- (prefix decrement operator)",
            "-= (minus-equal punctuator)", "-= (subtraction assignment operator)", "-> (minus-greater punctuator)",
            "-> (structure/union pointer operator)", ". (dot punctuator)", ". (structure/union member operator)",
            "... (ellipsis punctuator)", "/ (division operator)", "/ (slash punctuator)", "/= (division assignment operator)",
            "/= (slash-equal punctuator)", ": (colon punctuator)", ":> (colon greater punctuator)", "; (semicolon punctuator)",
            "< (less punctuator)", "< (less-than operator)", "<: (alternative spelling of [)", "<: (less-colon punctuator)",
            "<< (left-shift operator)", "<< (less-less punctuator)", "<<= (left-shift assignment operator)",
            "<<= (less-less equal punctuator)", "<= (less-equal punctuator)", "<= (less-than-or-equal-to operator)",
            "<% (alternative spelling of {)", "<% (less-percent punctuator)", "<assert.h> header", "<complex.h> header",
            "<ctype.h> header", "<errno.h> header", "<fenv.h> header", "<float.h> header", "<inttypes.h> header",
            "<iso646.h> header", "<limits.h> header", "<locale.h> header", "<math.h>", "<setjmp.h> header,",
            "<signal.h> header,",
            "<stdalign.h> header,",
            "<stdarg.h> header,",
            "<stdatomic.h> header,",
            "<stdbool.h> header,",
            "<stddef.h> header,",
            "<stdint.h> header,",
            "<stdio.h> header,",
            "<stdlib.h> header,",
            "<stdnoreturn.h> header,",
            "<string.h> header,",
            "<tgmath.h> header,",
            "<threads.h> header,",
            "<time.h> header,",
            "<uchar.h> header,",
            "<wchar.h> header,",
            "<wctype.h> header,",
            "= (equal-sign punctuator),",
            "= (simple assignment operator),",
            "== (equal-equal punctuator),",
            "== (equality operator),",
            "> (greater punctuator),",
            "> (greater-than operator),",
            ">= (greater-equal punctuator),",
            ">= (greater-than-or-equal-to operator),",
            ">> (greater greater punctuator),",
            ">> (right-shift operator),",
            ">>= (greater-greater-equal punctuator),",
            ">>= (right-shift assignment operator),",
            "? (question-mark punctuator),",
            "?: (conditional operator),",
            "?? (trigraph sequences),",
            "[ (opening bracket punctuator),",
            "[ ] (array subscript operator),",
            "[ ] (brackets punctuator),",
            "# format flag,",
            "% (percent punctuator),",
            "% (remainder operator),",
            "%: (percent-colon punctuator),",
            "%:%: (percent-percent punctuator),",
            "%= (percent-equal punctuator),",
            "%= (remainder assignment operator),",
            "%> (alternative spelling of }),",
            "%> (percent-greater punctuator),",
            "%A conversion specifier,",
            "%B conversion specifier,",
            "%C conversion specifier,",
            "%D conversion specifier,",
            "%E conversion specifier,",
            "%F conversion specifier,",
            "%G conversion specifier,",
            "%H conversion specifier,",
            "%I conversion specifier,",
            "%M conversion specifier,",
            "%R conversion specifier,",
            "%S conversion specifier,",
            "%T conversion specifier,",
            "%U conversion specifier,",
            "%V conversion specifier,",
            "%W conversion specifier,",
            "%X conversion specifier,",
            "%Y conversion specifier,",
            "%Z conversion specifier,",
            "& (address operator),",
            "& (ampersand punctuator),",
            "&= (ampersand-equal punctuator),",
            "&& (ampersand-ampersand punctuator),",
            "(backslash character),",
            "(backslash escape sequence),",
            "(single-quote escape sequence)",
            "(null character)",
            "padding of binary stream,",
            "(question-mark escape sequence)",
            " (universal character names)",
            "(alert escape sequence)",
            " (backspace escape sequence)",
            "(escape character)",
            "(form-feed escape sequence)",
            "(new-line escape sequence)",
            "octal digits (octal-character escape sequence),",
            "(carriage-return escape sequence)",
            "(horizontal-tab escape sequence)",
            "(universal character names),",
            "(vertical-tab escape sequence),",
            "{} (braces punctuator),",
            "{ (opening brace punctuator),",
            "} (closing brace punctuator),",
            "] (closing bracket punctuator),",
            "^ (bitwise exclusive OR operator),",
            "^ (caret punctuator),",
            "^= (bitwise exclusive OR assignment operator),",
            "^= (caret-equal punctuator),",
            "_Alignas,",
            "_Alignof operator,",
            "_Atomic type qualifier,",
            "_Atomic type specifier,",
            "_Bool type,",
            "_Bool type conversions,",
            "_C identifier suffix,",
            "_Complex type,",
            "_Complex types,",
            "_Complex_I macro,",
            "_Exit function,",
            "_Generic,",
            "_IOFBF macro,",
            "_IOLBF macro,",
            "_IONBF macro,",
            "_Imaginary keyword,",
            "_Imaginary type,",
            "_Imaginary types,",
            "_Imaginary_I macro,",
            "_MAX identifier suffix,",
            "_MIN identifier suffix,",
            "_Noreturn,",
            "_Pragma operator,",
            "_Static_assert,",
            "_Thread_local storage-class specifier,",
            "__STDC_ identifier prefix,",
            "__DATE__ macro,",
            "__FILE__ macro,",
            "__LINE__ macro,",
            "__STDC_ANALYZABLE__ macro,",
            "__STDC_HOSTED__ macro,",
            "__STDC_IEC_559_COMPLEX__ macro,",
            "__STDC_IEC_559__ macro,",
            "__STDC_ISO_10646__ macro,",
            "__STDC_LIB_EXT1__ macro,",
            "__STDC_MB_MIGHT_NEQ_WC__ macro,",
            "__STDC_NO_ATOMICS__ macro,",
            "__STDC_NO_COMPLEX__ macro,",
            "__STDC_NO_THREADS__ macro,",
            "__STDC_NO_VLA__ macro,",
            "__STDC_UTF_16__ macro,",
            "__STDC_UTF_32__ macro,",
            "__STDC_VERSION__ macro,",
            "__STDC_WANT_LIB_EXT1__ macro,",
            "__STDC__ macro,",
            "__TIME__ macro,",
            "__VA_ARGS__ identifier,",
            "__alignas_is_defined macro,",
            "__alignof_is_defined macro,",
            "__bool_true_false_are_defined macro,",
            "__cplusplus macro,",
            "__func__ identifier,",
            "_explicit identifier suffix,",
            "_t identifier suffix,",
            "| (bitwise inclusive OR operator),",
            "| (vertical-line punctuator),",
            "|= (bitwise inclusive OR assignment operator),",
            "|= (vertical-line-equal punctuator),",
            "|| (logical OR operator),",
            "|| (vertical-vertical punctuator),",
            "~ (bitwise complement operator),",
            "~ (tilde punctuator),",
            "0 format flag,",
            "abort function,",
            "abort_handler_s function,",
            "abs function,",
            "abs macro,",
            "absolute-value functions",
            "complex,",
            "integer,",
            "real,",
            "abstract declarator,",
            "abstract machine,",
            "access",
            "accuracy, see floating-point accuracy",
            "acos function",
            "acos type-generic macro",
            "acosf function",
            "acosh function",
            "acosh type-generic macro",
            "acoshf function",
            "acoshl function",
            "acosl function",
            "acquire fence",
            "acquire operation",
            "active position",
            "addition assignment operator (+=)",
            "addition operator (+)",
            "additive expressions",
            "address constant",
            "address operator (&)",
            "address-free",
            "aggregate initialization",
            "aggregate types",
            "alert",
            "alert escape sequence (a)",
            "aliasing",
            "alignas macro",
            "aligned_alloc function",
            "alignment",
            "pointer",
            "structure/union member",
            "alignment header",
            "alignment specifier",
            "alignof macro",
            "allocated storage, order and contiguity",
            "alternative spellings header",
            "and macro",
            "AND operators",
            "bitwise (&)",
            "bitwise (&)",
            "bitwise assignment",
            "logical (&&)",
            "AND operators",
            "logical (&&)",
            "and_eq macro",
            "anonymous structure",
            "anonymous union",
            "ANSIEE 754",
            "ANSIEE 854",
            "argc (main function parameter)",
            "argument",
            "array",
            "default promotions",
            "function",
            "macro",
            "argument, complex",
            "argv (main function parameter)",
            "arithmetic constant expression",
            "arithmetic conversions",
            "arithmetic operators",
            "additive",
            "bitwise",
            "increment and decrement",
            "multiplicative",
            "shift",
            "unary",
            "arithmetic types",
            "arithmetic, pointer",
            "array",
            "argument",
            "declarator",
            "initialization",
            "multidimensional",
            "parameter",
            "storage order",
            "subscript operator ([ ])",
            "subscripting",
            "type",
            "type conversion",
            "variable length",
            "arrow operator (->)",
            "as–if rule",
            "ASCII code set",
            "asctime function",
            "asctime_s function",
            "asin function",
            "asin type-generic macro",
            "asinf function",
            "asinh function",
            "asinh type-generic macro",
            "asinhf function",
            "asinhl function",
            "asinl function",
            "assert macro",
            "assignment",
            "compound",
            "conversion",
            "expression",
            "operators",
            "simple",
            "associativity of operators",
            "asterisk punctuator (*)",
            "at_quick_exit function",
            "atan function",
            "atan type-generic macro",
            "atan2 function",
            "atan2 type-generic macro",
            "atan2f function",
            "atan2l function",
            "atanf function",
            "atanh function",
            "atanh type-generic macro",
            "atanhf function",
            "atanhl function",
            "atanl function",
            "atexit function",
            "atof function",
            "atoi function",
            "atol function",
            "atoll function",
            "atomic lock-free macros",
            "atomic operations",
            "atomic types",
            "ATOMIC_ identifier prefix",
            "atomic_ identifier prefix I",
            "atomic_bool type",
            "ATOMIC_BOOL_LOCK_FREE macro",
            "atomic_char type",
            "atomic_char16_t type",
            "ATOMIC_CHAR16_T_LOCK_FREE macro",
            "atomic_char32_t type",
            "ATOMIC_CHAR32_T_LOCK_FREE macro",
            "ATOMIC_CHAR_LOCK_FREE macro",
            "atomic_compare_exchange_strong function",
            "atomic_compare_exchange_strong_explicit function",
            "atomic_compare_exchange_weak function",
            "atomic_compare_exchange_weak_explicit function",
            "atomic_exchange function",
            "atomic_exchange_explicit function",
            "atomic_fetch_ function",
            "atomic_flag type",
            "atomic_flag_clear function",
            "atomic_flag_clear_explicit function",
            "ATOMIC_FLAG_INIT macro",
            "atomic_flag_test_and_set function",
            "atomic_flag_test_and_set_explicit function",
            "atomic_init function",
            "atomic_int type",
            "atomic_int_fast16_t type",
            "atomic_int_fast32_t type",
            "atomic_int_fast64_t type",
            "atomic_int_fast8_t type",
            "atomic_int_least16_t type"
    };


    private String getRandomEntry(String[] array) {
        // Check if the array is not empty
        if (array.length == 0) {
            return "Array is empty"; // or some appropriate value
        }

        int randomIndex = random.nextInt(array.length);
        return array[randomIndex];
    }

    public String getRandomCompilerOpt() {
        return getRandomEntry(m_compilerOpt);
    }

    public String getRandomCompilerParts() {
        return getRandomEntry(m_compilerParts);
    }

    public String getRandomPL() {
        return getRandomEntry(m_PL);
    }
}
